name: CI - Analytics Service

on:
  push:
    branches: [main]
    paths: ["services/analytics-service/**"]
  pull_request:
    branches: [main]
    paths: ["services/analytics-service/**"]

jobs:
  ci:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      service_name: analytics-service
      service_path: services/analytics-service
      language: python
      ecr_repository: togglemaster/analytics-service
    secrets: inherit
